### ISSUE TITLE
compatible with v1.7.1

### ISSUE THREAD

**Issue by a632079** [julianlam/nodebb-plugin-sso-github#10]
Now, its status bar is not work.
![default](https://user-images.githubusercontent.com/16975812/33516815-f99ccf16-d7b3-11e7-8130-df116f921445.png)

**Comment by julianlam** [comment]
Hi there, what is it supposed to say? I don't recognize that text...

**Comment by a632079** [comment]
1.7.x It needs a whitelist in `user.getUserField`.It usually means that can't get `githubid` from database

**Comment by julianlam** [comment]
Oh, yes, thank you 😄 Will get this sorted out.

**Comment by julianlam** [comment]
v2.2.0 👍
