### ISSUE TITLE
Github SSO doesn't get the user email

### ISSUE THREAD

**Issue by digitalLumberjack** [julianlam/nodebb-plugin-sso-github#4]
Please include the following information when submitting a bug report/issue:
- NodeBB version and git hash : v1.1.0
- Exact steps to cause this issue
  1. Install github sso plugin
  2. Activate your plugin with credential
  3. Connect with github sso login
- What you expected
  - User real email fetched, in oder to use it for notifications and updates.
- What happened instead
  - users.noreply.github.com email created because the email is not returned in the profile from github if it's not public. It must be fetched from the api. The main issue is that users.noreply.github.com is not an domain (nslookup users.noreply.github.com returns NXDOMAIN) so we cannot send email to anyuser@users.noreply.github.com.

I contacted github because i though it was an issue from their dns, but they do not allow people to send emails on this domain.

Thank you!

**Comment by revir** [comment]
@digitalLumberjack 
The new plugin should have solved this problem, it can fetch non-public emails as well.
The issue should be closed.

**Comment by digitalLumberjack** [comment]
@revir tester and approved :)

Thank to the nodebb team !
